version: "3.0"
services:
    fluctuation-filter:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        environment:
            MODULE_NAME: "fluctuation-filter"
            MODULE_TYPE: "Processing"
            INGRESS_HOST: "0.0.0.0"
            INGRESS_PORT: "80"
            EGRESS_URLS: "https://webhook.site/81612398-a410-41bd-a8f9-d744b720924b"
            SEND_ON_CHANGE: "true"
            INPUT_LABEL: "event_code"
            WINDOW_SIZE: 1
        ports:
            - 8181:80
